fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google, -i]
        exclude: ^(include/cynetworklib|include/ihb-pc-shared|skin-ihb-pc-shared)/
      - id: cpplint
        exclude: ^(include/cynetworklib|include/ihb-pc-shared|skin-ihb-pc-shared)/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^(include/cynetworklib|include/ihb-pc-shared|skin-ihb-pc-shared)/